# DETERMINAN

Asumsikan A adalah suatu matriks bujur sangkar, fungsi
determinan, det(A) adalah jumlah semua hasil kali dasar
bertanda dari A. atau Determinan ordo n ialah suatu skalar yang terkait dengan
sebuah matriks bujur sangkar A yang berordo n.

## MINOR & KOFAKTOR DETERMINAN

- Jika A adalah suatu matriks bujur sangkar, maka Minor
elemen aij (Mij) didefinisikan sebagai determinan submatriks yang masih tersisa setelah baris ke-i dan kolomke-j dihilangkan
- Kofaktor elemen aij dinyatakan sebagai $k_{ij} = (-1)^{i+j} M_{ij}$

## SIFAT-SIFAT DETERMINAN

- det(A) = 0 jika dalam suatu baris/kolom semua elemennya
nol
- det(A) = det(AT)
- Nilai determinan menjadi k kali bila dalam satu
baris/kolom dikalikan dengan k (suatu skala).
- det(A) = 0 jika 2 baris/kolom sebanding.
-  Nilai determinan berubah tanda jika dua baris/kolomditukar tempatnya
- Nilai determinan tidak berubah jika baris/kolom ke – i
ditambah k kali baris/kolom ke – j.

In [ ]:
# import library numpy
import numpy as np

def RowSwap(A,k,l):
# =============================================================================
#     A adalah sebuah NumPy array.  RowSwap akan menghasilkan duplicate dari
#     array dengan baris k dan l di tukar
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowScale akan menghasilkan duplicate dari
#     array dengan baris k di kali dengan skalar bukan 0
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A adalah sebuah NumPy array.  RowAdd akan menghasilkan duplicate dari
#     array dengan baris k akan di kali dengan 'scale' bukan 0. lalu nilai
#     baris l akan di tambah dengan nilai baris k yang sudah dikalikan
# =============================================================================
    m = A.shape[0]  # m adalah nomor baris di A
    n = A.shape[1]  # n adalah nomor kolom di A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [ ]:
import numpy as np

A = np.array([[1, 3], [3, 1]])
B = np.array([[4, 2, 3], [2, 1, 3], [1, 2, 2]])
C = np.array([[2, 0], [3, 1]])
D = np.array([[1, 2, 0], [3, 1, 0], [2, 0, 1]])

print(A)
print(B)
print(C)
print(D)




[[1 3]
 [3 1]]
[[4 2 3]
 [2 1 3]
 [1 2 2]]
[[2 0]
 [3 1]]
[[1 2 0]
 [3 1 0]
 [2 0 1]]


## Determinan dari sebuah matriks identitas = 1 ##

In [ ]:
E = np.linalg.det(C)
F = np.linalg.det(D)
a = np.linalg.det(A)
b = np.linalg.det(B)

print(E)
print(F)
print(a)
print(b)

2.0
-5.000000000000001
-8.000000000000002
-8.999999999999998


## mencari invers matriks A

In [ ]:
G = np.linalg.inv(A)
H = np.linalg.inv(B)

print(G)
print(H)

[[-0.125  0.375]
 [ 0.375 -0.125]]
[[ 0.44444444 -0.22222222 -0.33333333]
 [ 0.11111111 -0.55555556  0.66666667]
 [-0.33333333  0.66666667  0.        ]]


## determinan i = det a . det a invers

In [ ]:
I = np.linalg.det(G)
J = np.linalg.det(H)

print(I)
print(J)

-0.12499999999999997
-0.11111111111111109


Sifat yang kedua  misalkan ab

det ab = det a . det b

---

i = a. a invers

det i = det a . det a invers

det a invers = 1/ det a

In [ ]:
e = np.array([[2,1,1],[1,3,2],[2,3,1]])
f = np.array([[1,4,2],[2,1,3],[2,3,2]])

print(e)
print(f)

[[2 1 1]
 [1 3 2]
 [2 3 1]]
[[1 4 2]
 [2 1 3]
 [2 3 2]]


In [ ]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [ ]:
a = np.linalg.det(A)

print(a.round())

5.0


## merubah baris darisebuah matriks akan merubah sebuah tanda dari determinan

In [ ]:
A1 = np.array([[1,1,1],[1,4,2],[3,2,1]])

print(A1)

[[1 1 1]
 [1 4 2]
 [3 2 1]]


In [ ]:
a = np.linalg.det(A1)

print(a.round())

-5.0


## merubah kolom pada matriks

In [ ]:
A = np.array([[4,1,2],[1,1,1],[2,3,1]])

print(A)

[[4 1 2]
 [1 1 1]
 [2 3 1]]


In [ ]:
a = np.linalg.det(A)

print(a.round())

-5.0


Penjelasan :
- jika baris dari matrik merupakan kelipatan dari baris yang lain maka nilai matriks determinan yang ada sama dengan 0
- kelipatan baris matriknya adalah 2 kali matriks awal

In [ ]:
B = np.array([[1,4,2],[2,8,4],[3,2,1]])

print(B)

[[1 4 2]
 [2 8 4]
 [3 2 1]]


In [ ]:
b = np.linalg.det(B)

print(b.round())

0.0


k = skala

A = matriks nxn

det k.A = K pangkat n dikali det A

In [ ]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [ ]:
a = np.linalg.det(A)

print(a.round())

5.0


In [ ]:
KA = np.array([[2,8,4],[2,2,2],[6,4,2]])

print(KA)


[[2 8 4]
 [2 2 2]
 [6 4 2]]


det (KA) = 2 pangkat 3 . 5

         = 40

In [ ]:
b = np.linalg.det(KA)

print(b.round())

In [ ]:
B = np.array([[2,8,4],[1,1,1],[3,2,1]])

print(B)

[[2 8 4]
 [1 1 1]
 [3 2 1]]


= 2*Det A

maka dengan t adalah skala

maka det(b) = t kali dengan Det (A)

In [ ]:
b = np.linalg.det(B)

print(b.round())


10.0


##
- Matriks segitiga atas
dimana d bawah diagonal elemennya nol
-  matriks segitiga bawah
dimana diatas diagonal elemennya nol

det matrik segitiga adalah
det A = d1 kali d2 sampai dn
- perkalian pada setiap elemen diagonal matriksnya

In [ ]:
A = np.array([[2,3,1,2],[0,1,2,1],[0,0,5,2],[0,0,0,3]])

print(A)

[[2 3 1 2]
 [0 1 2 1]
 [0 0 5 2]
 [0 0 0 3]]


det (A) = 2.1.5.3 = 30

In [ ]:
a = np.linalg.det(A)

print(a.round())

5.0


Merubah nilai baris tidak merubah nilai determinan dari suatu matriks

In [ ]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [ ]:
a = np.linalg.det(A)

print(a.round())

5.0


In [ ]:
B = np.array([[1,4,2],[0,-3,-1],[3,2,1]])

print(B)

[[ 1  4  2]
 [ 0 -3 -1]
 [ 3  2  1]]


In [ ]:
b = np.linalg.det(a)
print(b.round())

14.0


det A transpose = det A

In [ ]:
A = np.array([[1,4,2],[1,1,1],[3,2,1]])

print(A)

[[1 4 2]
 [1 1 1]
 [3 2 1]]


In [ ]:
A1 = np.transpose(A)

print(A1)

[[1 1 3]
 [4 1 2]
 [2 1 1]]


In [ ]:
a = np.linalg.det(A1)

print(a.round())

5.0


## EKSPANSE KONFAKTOR
 adalah salah satu metode mencari determinan suatu matriks, di mana dalam metode ini memanfaatkan kofaktor. Pencarian determinan menggunakan metode ini tidak terbatas dengan satu ukuran matriks. Dengan kata lain, dapat dihitung matriks 3x3, 4x4, 5x5, dan seterusnya.

In [ ]:
a =np.array([[2,1,4,3],[3,2,1,1],[1,1,3,2],[4,3,2,4]])

print(a)

[[2 1 4 3]
 [3 2 1 1]
 [1 1 3 2]
 [4 3 2 4]]


In [ ]:
b = np.linalg.det(a)

print(b.round())

14.0


## CONTOH PENYELESAIAN MATRIKS DETERMINAN DENGAN METODE EKSPANSI KONFAKTOR

Menggunakan Matriks 4X4 sebagai berikut :

$ A = \begin{pmatrix}
2 & 1 & 4 & 3 \\
3 & 2 & 1 & 1 \\
1 & 1 & 3 & 2 \\
4 & 3 & 2 & 4 \\
\end{pmatrix} $

Rumus Penurunan Kofaktor dengan cara menangani ekspansi kofaktor 3×3 . Kita ambil submatriks kedua di atas dan dilambangkan dengan M :
- A31 C31 = $(-1)^{3+1}(det M31)$

Baik, mari kita hitung determinan untuk elemen \( A_{31} \) dengan menggunakan ekspansi kofaktor.


A
31
​
 C
31
​
 =(−1)
3+1
 det(M
31
​
 )


Di sini,  
(
−
1
)
3
+
1
(−1)
3+1


  adalah faktor kofaktor untuk elemen A
31
​
 , dan
det
(
𝑀
31
)
det(M
31
​
 )adalah determinan dari submatriks M
31
​
 .

Kita sudah menghitung determinan untuk M
31 sebelumnya, yang hasilnya adalah  
−
15
−15.. Mari kita substitusikan nilainya ke dalam rumus:

A
31
​
 C
31
​
 =(−1)
4
 (−15)
=
1
⋅
(
−
15
)
=1⋅(−15)
=
−
15
=−15

Jadi, nilai dari A
31
​
 C
31 adalah  -15.
- A32 C32 = $(-1)^{3+2}(det M32)$
- A33 C33 = $(-1)^{3+3}(det M33)$
- A34 C34 = $(-1)^{3+4}(det M34)$

$ M31 = \begin{pmatrix}
1 & 4 & 3 \\
2 & 1 & 1 \\
3 & 2 & 1 \\
\end{pmatrix}
M32 = \begin{pmatrix}
2 & 4 & 3 \\
3 & 1 & 1 \\
4 & 2 & 4 \\
\end{pmatrix}
M33 = \begin{pmatrix}
2 & 1 & 3 \\
3 & 2 & 1 \\
4 & 3 & 4 \\
\end{pmatrix}
M34 = \begin{pmatrix}
2 & 1 & 4 \\
3 & 2 & 1 \\
4 & 3 & 2 \\
\end{pmatrix} $


Hitung menangani Setiap ekspansi Kofaktor 2X2 dari M21. Kita ambil submatriks kedua di atas dan dilambangkan dengan detM :
- A11 C11 = $(-1)^{1+1}(det M11)$
- A31 C31 = $(-1)^{1+2}(det M31)$
- A11 C11 = $(-1)^{1+3}(det M11)$
- A11 C11 = $(-1)^{1+3}(det M11)$

Dimana Det:

$ M11 = \begin{pmatrix}
1 & 1 \\
2 & 4 \\
\end{pmatrix}
M12 = \begin{pmatrix}
2 & 1 \\
3 & 4 \\
\end{pmatrix}
M13 = \begin{pmatrix}
2 & 1 \\
3 & 2 \\
\end{pmatrix} $

Dimana Det:

$ M31 = \begin{pmatrix}
4 & 3 \\
1 & 1 \\
\end{pmatrix}
M32 = \begin{pmatrix}
2 & 3 \\
3 & 1 \\
\end{pmatrix}
M33 = \begin{pmatrix}
2 & 4 \\
3 & 1 \\
\end{pmatrix} $

Dimana Det:

$ M11 = \begin{pmatrix}
2 & 1 \\
3 & 4 \\
\end{pmatrix}
M12 = \begin{pmatrix}
3 & 1 \\
4 & 4 \\
\end{pmatrix}
M13 = \begin{pmatrix}
3 & 2 \\
4 & 3 \\
\end{pmatrix} $

Dimana Det:

$ M11 = \begin{pmatrix}
1 & 4 \\
3 & 2 \\
\end{pmatrix}
M12 = \begin{pmatrix}
2 & 4 \\
4 & 2 \\
\end{pmatrix}
M13 = \begin{pmatrix}
2 & 1 \\
1 & 3 \\
\end{pmatrix} $