# KONSEP EIGENVALUE DAN EIGENVEKTOR

# Konsep nilai eigen (eigenvalue) adalah bagian dari teori aljabar linear yang berkaitan dengan matriks dan transformasi linear. Berikut adalah penjelasan mendetail tentang konsep nilai eigen:

### Definisi Nilai Eigen
Definisi Nilai Eigen
Dalam aljabar linear, nilai eigen dari sebuah matriks
𝐴
A adalah skalar
𝜆
λ yang memenuhi persamaan berikut:


𝐴
𝑣
=
𝜆
𝑣
Av=λv


Di sini,
𝑣
v adalah vektor eigen (eigenvector) yang tidak nol. Persamaan ini menunjukkan bahwa ketika matriks
𝐴
A mengalikan vektor eigen
𝑣
v, hasilnya adalah vektor yang searah dengan
𝑣
v itu sendiri, hanya diperbesar atau diperkecil oleh faktor skalar
𝜆
λ.



# Menghitung Eigenvalues dan Eigenvectors

*Contoh*  
  
Hitung eigen value dan eigen vector dari matrik A  
  
$$
\begin{matrix}
    A = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
\end{matrix}
$$

solusi:  

$
\begin{matrix}
    A - \lambda = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    \lambda \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad
\quad
\begin{matrix}
    = \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    \begin{bmatrix}
        \lambda & 0 \\
        0 & \lambda \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad
\quad
\begin{matrix}
    = \begin{bmatrix}
        3 - \lambda & 5 \\
        4 & 2 - \lambda \\
    \end{bmatrix}
\end{matrix}
$

$
det(A - \lambda) = (3 - \lambda) (2 - \lambda) - 20 \\
$  

$
\qquad \qquad \quad = \lambda^2 + 6 - 2 \lambda - 3 \lambda - 20 \\
$  

$
\qquad \qquad \quad = \lambda^2 - 5 \lambda - 14
$  


$
\lambda^2 - 5 \lambda - 14 = 0 \\
$  
$
(\lambda - 7) (\lambda + 2) = 0 \\
$  
$
\lambda = 7 \space dan \space -2
$  

$Ax = 7x \space dan \space Ax = -2x$  
  
Untuk $\lambda = -2$  
  
$
A - (-2)! = \begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    +
    2 \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  

$
\qquad \qquad \quad
= \begin{matrix}
    \begin{bmatrix}
        5 & 5 \\
        4 & 4 \\
    \end{bmatrix}
\end{matrix}
$

dari matrix di atas di peroleh persamaan berikut

$x1 + x2 = 0$  
$x1 = -x2$  
$1.1 = -1.-1$  
$x1 = 1$  
$x2 = -1$  
  
$
\begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
        1 \\
        -1
    \end{bmatrix}
    = \begin{bmatrix}
        -2 \\
         2
    \end{bmatrix}
\end{matrix}
$  
  
untuk $\lambda = 7$  

$  
A - 7! = \begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    -
    7 \begin{bmatrix}
        1 & 0 \\
        0 & 1 \\
    \end{bmatrix}
\end{matrix}
$  
    
$
\qquad \qquad \quad
= \begin{matrix}
    \begin{bmatrix}
        -4 & 5 \\
        4 & -5 \\
    \end{bmatrix}
\end{matrix}
$

dari matrix di atas di dapatkan persamaan:
$-4x1 + 5x2 = 0$  
$5x2 = 4x1$  
$x1 = 1.25$  
$x2 = 1$  
  
$
\begin{matrix}
    \begin{bmatrix}
        3 & 5 \\
        4 & 2 \\
    \end{bmatrix}
    \begin{bmatrix}
        1.25 \\
        1
    \end{bmatrix}
    = \begin{bmatrix}
        8.75 \\
        7
    \end{bmatrix}
\end{matrix}
$  


eignvalue = [7, -2]  
eignvector = [[1,1], [1,-1]]
  
untuk $\lambda = $ 7 dan $x =$ [1,1]  
   
$
\begin{matrix}
    A x = \begin{bmatrix}
       8.75 \\
       7   
    \end{bmatrix}
    =
    \lambda x = \begin{bmatrix}
        8.75 \\
        7
    \end{bmatrix}
\end{matrix}
$

untuk $\lambda = $ -2 dan $x =$ [1,-1]  
  

$
\begin{matrix}
    A x = \begin{bmatrix}
       -2 \\
        2  
    \end{bmatrix}
    =
    \lambda x = \begin{bmatrix}
        -2 \\
         2
    \end{bmatrix}
\end{matrix}
$





# Mencari nilai eigen value dan eigen vector pada matriks 2x2 menggunakan numpy

In [7]:
import numpy as np
from numpy.linalg import eig
a = np.array([[1,2],[2,3]])
W,V = eig(a)

print('value',W)
print('vector',V.round())

value [-0.23606798  4.23606798]
vector [[-1. -1.]
 [ 1. -1.]]


# Mencari nilai eigen value dan eigen vector pada matriks 3x3 menggunakan numpy

In [6]:
import numpy as np
from numpy.linalg import eig
a = np.array([[2,4,1],[2,1,1],[3,1,4]])
W,V = eig(a)

print('value',W.round())
print('vector',V.round())

value [ 6. -1.  2.]
vector [[-0. -1. -1.]
 [-0.  1. -0.]
 [-1.  0.  1.]]


# Contoh Implementasi Eigenvalue dan Eigenvector

In [8]:
import numpy as np

# Definisikan matriks 2x2
A = np.array([[4, 1],
              [2, 3]])
eigenvalues, eigenvectors = np.linalg.eig(A)

# Cetak hasil
print("Matriks A:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)


Matriks A:
[[4 1]
 [2 3]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]
